### ISSUE TITLE
encode and decode URL paramters

### ISSUE THREAD

**Issue by kamarton** [yiisoft/router#10]
### What steps will reproduce the problem?

I do not want the URLs to have the values ​​in their original form, so I have to encode all the places where they occur. And when I receive an incoming request, I always have to decoding it.

example `id -> hashids.org -> id`

Cases when this is needed:
- value has sensitive data
- I want to make page scanners harder.
- value is binary string
- value is too long

### What is the expected result?

```php
Route::get('/test/{id:\w+}')->encodeParameters(function($parameter, $value) {
  if($parameter != 'id') {
    return $value;
  }
  return base64_encode($value);
})->decodeParameters(function($parameter, $value) {
  if($parameter != 'id') {
    return $value;
  }
  return base64_decode($value);
})....
```

### What do you get instead?

example (yii2):

```php
Url::to('test', ['id' => base64_encode($id)]);   // All places where they occur in the code.

public function run($id) {
  $id = base64_decode($id);  // All places where they occur in the code.
}
```

| Q                | A
| ---------------- | ---
| Version          | 1.0.0 under development
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
I think that is out of scope or router. Need more opinions. @yiisoft/reviewers?

**Comment by kamarton** [comment]
For me, it is acceptable to have another layer, the important thing is to do the encoding and decoding automatically. (I don't see the full request process yet.)

**Comment by samdark** [comment]
That could be done with a decorator implementing UrlGeneratorInterface and UrlMatcherInterface. I still think that it's not that common to have it in the one of framework packages out of the box.

**Comment by kamarton** [comment]
The encode is by no means part of it, I see it. 

```php
Route::get('/test/{id:\w+}')->proxy(function($request) {
   return $request->set('id', decode($request->get('id')));
})
```
Could it be an alternative? I could imagine a proxy function for other uses.

**Comment by kamarton** [comment]
> That could be done with a decorator implementing UrlGeneratorInterface and UrlMatcherInterface. I still think that it's not that common to have it in the one of framework packages out of the box.

I don't see the new system yet, so I accept what you wrote.
