### ISSUE TITLE
Error with multiple routes files: prependMiddleware() can not be used before action()

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/router#100]
### What steps will reproduce the problem?
```php
return [
    RouteCollectionInterface::class => static function (ApplicationParameters $appParams, RouteCollectorInterface $collector) use ($config) {
        $collector
            ->middleware(CsrfMiddleware::class)
            ->middleware(FormatDataResponse::class)
            ->addGroup(
                Group::create()->routes(...$config->get("routes-{$appParams->site}")),
            )
            ->addGroup(
                Group::create()->routes(...$config->get("routes-{$appParams->siteReversed}"))
            );

        return new RouteCollection($collector);
    },
];
```

I am not using `prependMiddleware` in my config and/or config anywhere. For testing purposes I have commented out every `middleware` in my routes as well.

### What do you get instead?
`prependMiddleware() can not be used before action().`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8.0.3
| Operating system | Debian 10

**Comment by yiiliveext** [comment]
Any route must contains action() method.

**Comment by Mister-42** [comment]
> Any route must contains action() method.

Why?
```php
        Route::get('orig')
            ->middleware(fn (Redirect $redirect) => $redirect->toRoute('new')),
```

What would be the action here?

**Comment by yiiliveext** [comment]
> > Any route must contains action() method.
> 
> Why?
> 
> ```
>         Route::get('orig')
>             ->middleware(fn (Redirect $redirect) => $redirect->toRoute('new')),
> ```
> 
> What would be the action here?

Redirect is the action.

**Comment by Mister-42** [comment]
> Redirect is the action.

No, that is middleware and this rule failes with above very abstract error unless an empty action is added.

**Comment by Mister-42** [comment]
Also, this should be completely valid for its purpose:

```php
    // Assets for urlGenerator, requests will not be handled by Yii
    Route::get('/images/{file}')
        ->host($appParams->assetDomain)
        ->name('img'),
```

**Comment by yiiliveext** [comment]
> Also, this should be completely valid for its purpose:
> 
> ```
>     // Assets for urlGenerator, requests will not be handled by Yii
>     Route::get('/images/{file}')
>         ->host($appParams->assetDomain)
>         ->name('img'),
> ```

I don't think this is the right way to use routes.

**Comment by Mister-42** [comment]
@samdark Would that be a valid use case?

**Comment by yiiliveext** [comment]
> @samdark Would that be a valid use case?

Anyway you can solve the problem by creating a separate group for those routes.

**Comment by Mister-42** [comment]
I don't think I understand you there. How would that solve the issue?

**Comment by yiiliveext** [comment]
> I don't think I understand you there. How would that solve the issue?

```php
RouteCollectionInterface::class => static function (RouteCollectorInterface $collector) use ($config) {
        $collector
            ->middleware(CsrfMiddleware::class)
            ->middleware(FormatDataResponse::class)
            ->addGroup(
                Group::create()
                    ->routes(...$config->get('routes'))
            );
        $vitrualRoutesForUrlGeneratorOnly = Group::create()
            ->routes(
                Route::get('/images/{file}')
                    ->host($appParams->assetDomain)
                    ->name('img'),
            );
        $root = Group::create()->routes($collector, $vitrualRoutesForUrlGeneratorOnly);

        return new RouteCollection($root);
    },
```

Of course you can get virtual routes form a separate file, this is just an example.

**Comment by Mister-42** [comment]
Not very intuitive, but I can confirm it works 👍🏻

**Comment by yiiliveext** [comment]
> Not very intuitive, but I can confirm it works 👍🏻

I think we will make `static()` method for those routes.
