### ISSUE TITLE
Add a warning about the prohibition of use group and route interfaces

### ISSUE THREAD

**Issue by vjik** [yiisoft/router#130]
`GroupInterface`, `RouteInterface` and `RouteParametersInterface` has one implementation each in package and shouldn't implement somewhere else. This interfaces need only for convient IDE autocomplete.

I think this warning should be in phpdoc of interfaces.

**Comment by samdark** [comment]
Likely it is a good idea to remove these interfaces and try another way of passing data around such as having a single getter returning a DTO or even an array.
