### ISSUE TITLE
Psalm error on use `RouteCollectorInterface::addGroup()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/router#131]
`RouteCollectorInterface::addGroup()` accepts parameter with type `Group`, but `Group::create()` returns `GroupInterface`:

![image](https://user-images.githubusercontent.com/525501/143257286-214ba2f2-5da7-4b53-97d4-c36965e9dd75.png)

**Comment by samdark** [comment]
Should use interface if possible.

**Comment by vjik** [comment]
No, we don't can use interface in `addGroup()` because need object with getters, but interface contain only setters.
