### ISSUE TITLE
Use variadic argument in `Group::middleware()`, `Group::prependMiddleware()` and similar methods

### ISSUE THREAD

**Issue by vjik** [yiisoft/router#141]
- `Group::middleware()`
- `Group::prependMiddleware()`
- `Route::middleware()`
- `Route::prependMiddleware()`
- `RouteCollector::middleware()`
- `RouteCollector::prependMiddleware()`

**Comment by samdark** [comment]
Currently the syntax is:

```php
Route::get('/api/bla-bla')
  ->middleware(Authenticate::class)
  ->middleware(FormatDataResponseAsHtml::class)
```

I'm not sure the following will be better:

```php
Route::get('/api/bla-bla')
  ->middleware(
    Authenticate::class,
    FormatDataResponseAsHtml::class
  )
```

**Comment by vjik** [comment]
Current syntax will remain available. Variadic is optional.
