### ISSUE TITLE
Remove variadics

### ISSUE THREAD

**Issue by samdark** [yiisoft/router#149]
1. Two ways to do the same thing.
2. Not obvious about the order: https://github.com/yiisoft/router/pull/147/files#diff-7c55babf7041639cd7afeb7dd9692594656cfa9fcee1fe4dfec3a1d3d06c3f0eR77

**Comment by samdark** [comment]
See https://github.com/yiisoft/router/commit/ab74b9ef8bc9a9ea2bfea99ebc1f0a76f6e9f96b

**Comment by vjik** [comment]
> 1. Two ways to do the same thing.

One way — using one method, for example `middleware()`.

> 2. Not obvious about the order: https://github.com/yiisoft/router/pull/147/files#diff-7c55babf7041639cd7afeb7dd9692594656cfa9fcee1fe4dfec3a1d3d06c3f0eR77

In PHP has functions [array_push](https://www.php.net/manual/ru/function.array-push.php) and [array_unshift](https://www.php.net/manual/ru/function.array-unshift.php) that do the same thing, and they work obvious, without causing problems.

**Comment by samdark** [comment]
OK.
