### ISSUE TITLE
Refactor Route factory methods

### ISSUE THREAD

**Issue by xepozz** [yiisoft/router#18]
At now we can create `Route` without name. But without name `Route` is useless (for generating we need to know name which url we want to generate, but we don't know it).

I suggest to make one of following solutions:
1. Create RouteBuilder
  RouteBuilder will sets to private properties intermediate results that allowed to build `Route` step-by-step.  
2. Extend `get`, `post`, `patch` and other methods with required argument `name`.

After each of solutions Route will be created over `__construct` method instead of setting private methods directly.

Which problem will be solved?
At now `name` is optional property as declared, but in real case it's required property.

**Comment by rob006** [comment]
> But without name `Route` is useless (for generating we need to know name which url we want to generate, but we don't know it).

You don't need a name if rule is never used for generating URL.

**Comment by xepozz** [comment]
Then this route is not needed. It makes no sense to add it to the collection of routes

**Comment by rob006** [comment]
It could be used only for parsing request. Yii 2 has separate switch for this: https://www.yiiframework.com/doc/api/2.0/yii-web-urlrule#$mode-detail

**Comment by xepozz** [comment]
Ok. In this case route should be generated with unique name. (ex. hash based on route pattern or other)

**Comment by samdark** [comment]
Why do we need to generate it if it won't be used?

**Comment by xepozz** [comment]
I was thinking about it today some time.
You are right, route can exists without name. But without a handler it's difenitely useless. If it will use only for parsing and will nothing to handle it's difenitely useless and invalid.

Upd: If we won't generate a name by default name will equal to pattern.

For notes: route name needs to show in Debugger

**Comment by samdark** [comment]
Yes, a route without a handler isn't useful.

**Comment by samdark** [comment]
We don't need a builder or any extra abstraction layer to solve it. Currently it's, indeed, possible to define a route w/o handler. That could be solved in multiple ways.

## Making handler mandatory in Route

```php
Route::get('/bla-bla', $middleware)
    ->name('bla-bla')
    ->then($anotherMiddleware);
```

## Throwing an exception in RouteCollectorInterface::addRoute

If there's a route w/o handler encountered, throw an exception here: https://github.com/yiisoft/router/blob/master/src/Group.php#L23

Then the syntax stays the same:

```php
Route::get('/bla-bla')
    ->name('bla-bla')
    ->to($middleware)
    ->then($anotherMiddleware);
```

**Comment by rob006** [comment]
> Currently it's, indeed, possible to define a route w/o handler.

Is it really a problem? In Yii 2 you can have rule used only for generating URLs - you don't need a handler in that case.

**Comment by xepozz** [comment]
I vote for the first proposal because it may and should use `__construct` "under the hood"

**Comment by samdark** [comment]
@rob006 was it valid case to generate URLs that would not resolve because there is no handler?

**Comment by rob006** [comment]
> @rob006 was it valid use case to generate URLs that would not resolve because there is no handler?

Generating URLs to external services, for example from `example.com` to `api.example.com` - `api.example.com` needs routing only with handlers (routing is used only for handling request), and `example.com` needs the same routing but only with names (routing is used only for generating URLs to `api.example.com`).

**Comment by samdark** [comment]
Yes, makes sense. So handler isn't strictly mandatory.

**Comment by samdark** [comment]
So it seems there's nothing to fix then.
