### ISSUE TITLE
Support short action syntax

### ISSUE THREAD

**Issue by xepozz** [yiisoft/router#211]
It would be great to support short class+method reference for the end point of route stack called `action`.

```php
class Handler1 implements \Psr\Http\Server\RequestHandlerInterface {
  public function handle(...) {...}
}

class Handler2 {
  public function __invoke(...) {...}
}

// feature request 

$route->action(Handler1::class);
$route->action(Handler2::class);

// how it looks now

$route->action([Handler1::class, 'handle']);
$route->action([Handler2::class, '__invoke']);

```

**Comment by vjik** [comment]
Seems, invokeable classes is support, because it callable.

**Comment by vjik** [comment]
Maybe add this to `yiisoft/middleware-dispatcher` also?

**Comment by samdark** [comment]
Won't hurt but is less needed there since middleware are rarely defined as callables or controllers.

**Comment by vjik** [comment]
> Won't hurt but is less needed there since middleware are rarely defined as callables or controllers.

Yes, but better to do it right away in middleware dispatcher. And, seems, it's not need changes in router, update middleware dispatcher will be enough.

**Comment by samdark** [comment]
Alright.

**Comment by xepozz** [comment]
Shall we close it?
