### ISSUE TITLE
Callback middleware bug?

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/router#22]
### What steps will reproduce the problem?
When pass callable array instead of ActionCaller
```php
Route::get('/', [SiteController::class, 'index'])
                ->name('site/index')
```
### What is the expected result?
Should work
### What do you get instead?
Error: `Using $this when not in object context`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4
| Operating system | Debian

**Comment by yiiliveext** [comment]
It's not a bug. This syntax is not allowed, just use the ActionCaller. 
If you have a case where you can't use it, let me know.
