### ISSUE TITLE
Improve Group

### ISSUE THREAD

**Issue by xepozz** [yiisoft/router#30]
### Subject 
At now `Group` has 2 difference ways to create itself. 
1. `new Group($prefix, callable $callback, $container)`
2. `Group::create($prefix, array $routes, $container)`

I suggest to combine this 2 methods to one: `Group::create($prefix, array|callable $routes, $container)`

### Why?
1. Uniform code is more simpler and cleaner.
2. Developer no need to remebmer all ways to create the same object.

### Why static factory method instead of the `new` operator?
Because `Route` has no way to create itself with the `new` operator.

**Comment by samdark** [comment]
Sounds good to me.

**Comment by mapeveri** [comment]
I sent a PR related to this issue :)
