### ISSUE TITLE
Group route parameters in a Request attributes

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/router#55]
I believe that it would be more correct if the router writes route parameters to its group in the attributes, and not as it is now

```php
Route::get('/test/{id:\w+}/{param1}[/{param2}]', ...);
```

Now, if we request the attributes of the request, we get
```php
[
    // Route params
    'id' => ...,
    'param1' => ...,
    'param2' => ...,
    // From middlewares
    'language' => 'en',
    'format' => 'json',
    '...' => ...
]
```
What happens if we set a competing `format` parameter in the route?

When implementing my proposal:
```php
[
    // Route params
    'router' => [
        'id' => ...,
        'param1' => ...,
        'param2' => ...,
    ]
    // From middlewares
    'language' => 'en',
    'format' => 'json',
    '....' => ...
]
```
No conflicts. And we can always separate route parameters from others

**Comment by samdark** [comment]
I like and dislike the idea. It resolves potential conflicts (and there's no doubt there are going to be conflicts since both sides are developer-powered) but it makes working with request parameters less appealing:

```php
public function actionConfirm(ServerRequestInterface $request)
{
    $id = $request->getAttribute('router', [])['id'] ?? null;
    $code = $request->getAttribute('router', [])['code'] ?? null;
    // ...
}
```

vs current:

```php
public function actionConfirm(ServerRequestInterface $request)
{
    $id = $request->getAttribute('id');
    $code = $request->getAttribute('code');
    // ...
}
```

**Comment by viktorprogger** [comment]
@roxblnfk Can you explain please the usecase for this?

**Comment by samdark** [comment]
We may add ability to get matched arguments from CurrrentRoute. Then we can remove writing arguments to request.
