### ISSUE TITLE
Do not use Method::ALL

### ISSUE THREAD

**Issue by samdark** [yiisoft/router#64]
1. See https://github.com/yiisoft/http/issues/12
2. ANY should be a method within router package and a list of methods should be configurable.

**Comment by samdark** [comment]
ANY could actually be named as REST so it's not used for regular GET/POST web routes.

**Comment by xepozz** [comment]
> ANY could actually be named as REST so it's not used for regular GET/POST web routes.

Do you mean REST as "specification"?

**Comment by samdark** [comment]
Yes.

**Comment by xepozz** [comment]
What's the reason to make router dependable on different specifications?

**Comment by samdark** [comment]
None. We haven't implemented that.
