### ISSUE TITLE
Dispatcher's method withMiddlewares has potential bug

### ISSUE THREAD

**Issue by denyadzi** [yiisoft/router#66]
Continuing with my interest in middleware dispatching in Yii3. Here I've noticed a kind of logical problem with Dispatcher::withMiddlewares method. One may expect, that giving a new set of middlewares to it will change the workflow the dispatch-method will do. But it doesn't work in this way due to the handler-stack being built for first set of middlewares only.

### What steps will reproduce the problem?

I've written a little test that demonstrates that https://github.com/denyadzi/router/blob/dispatcher-with-middlewares-issue/tests/DispatcherTest.php

### Possible solution 

Stack should be nulled together with middlewares assignment, but this will make stack being rebuilt all the time, as this method is called in MatchingResult. Possibly [this approach](https://github.com/yiisoft/yii-web/pull/307/commits/e51214bfccc15b6581966c34d2ae9d284f15186a) could be useful here

**Comment by yiiliveext** [comment]
Dispatcher can't be called twice with different middleware sets. Though, the code really looks a little bit strange. I'll look, how we can do it clearer.

**Comment by yiiliveext** [comment]
> 
> ### What steps will reproduce the problem?
> I've written a little test that demonstrates that https://github.com/denyadzi/router/blob/dispatcher-with-middlewares-issue/tests/DispatcherTest.php

This test is incorrect, `Dispatcher` is immutable, so you can't reproduce this case in a real application with a container.
The correct test is:
```php
public function testWithMiddlewares_shouldAffectFlow()
    {
        $middleware200 = $this->createMock(MiddlewareInterface::class);
        $middleware200
            ->method('process')
            ->willReturn(new Response(200));
        $middleware400 = $this->createMock(MiddlewareInterface::class);
        $middleware400
            ->method('process')
            ->willReturn(new Response(400));

        $request = new ServerRequest('GET', '/');
        $fallbackHandler = $this->createMock(RequestHandlerInterface::class);

        //dispatcher that stored in the container;
        $dispatcher = $this->container->get(Dispatcher::class);

        //dispatcher in the first request
        $firstDispatcher = $dispatcher->withMiddlewares([$middleware200]);
        $response200 = $dispatcher->dispatch($request, $fallbackHandler);
        //dispatcher in the second request
        $secondDispatcher = $firstDispatcher->withMiddlewares([$middleware400]);
        $response400 = $secondDispatcher->dispatch($request, $fallbackHandler);

        $this->assertEquals(200, $response200->getStatusCode());
        $this->assertEquals(400, $response400->getStatusCode());
    }
```
or this one
```php
public function testWithMiddlewares_shouldAffectFlow()
    {
        $middleware200 = $this->createMock(MiddlewareInterface::class);
        $middleware200
            ->method('process')
            ->willReturn(new Response(200));
        $middleware400 = $this->createMock(MiddlewareInterface::class);
        $middleware400
            ->method('process')
            ->willReturn(new Response(400));

        $request = new ServerRequest('GET', '/');
        $fallbackHandler = $this->createMock(RequestHandlerInterface::class);

        //first request
        $dispatcher = $this->container->get(Dispatcher::class)->withMiddlewares([$middleware200]);;
        $response200 = $dispatcher->dispatch($request, $fallbackHandler);
        
        //second request
        $secondDispatcher = $this->container->get(Dispatcher::class)->withMiddlewares([$middleware400]);
        $response400 = $secondDispatcher->dispatch($request, $fallbackHandler);

        $this->assertEquals(200, $response200->getStatusCode());
        $this->assertEquals(400, $response400->getStatusCode());
    }
```

**Comment by yiiliveext** [comment]
> Stack should be nulled together with middlewares assignment, but this will make stack being rebuilt all the time, as this method is called in MatchingResult. 

I've created pr, but this is really a bad way for using with request loop.

**Comment by yiiliveext** [comment]
Another solution
https://github.com/yiisoft/router/pull/68

**Comment by denyadzi** [comment]
What is the reason of initializing dispatcher with middlewares [in this place in MatchResult](https://github.com/yiisoft/router/blob/master/src/MatchingResult.php#L78). If it's supposed to be initialized once, could it be done conditionally [here](https://github.com/yiisoft/router/blob/master/src/MatchingResult.php#L75) in some way?

**Comment by yiiliveext** [comment]
> What is the reason of initializing dispatcher with middlewares [in this place in MatchResult](https://github.com/yiisoft/router/blob/master/src/MatchingResult.php#L78). If it's supposed to be initialized once, could it be done conditionally [here](https://github.com/yiisoft/router/blob/master/src/MatchingResult.php#L75) in some way?

The reason is the route caching. On the other hand, we should inject the dispatcher in a way wich makes possible to reuse stack, that was built in the previouse request.

**Comment by denyadzi** [comment]
@yiiliveext could the dispatcher with middlewares and built stack been cached with route? Please see #69 for what I mean, though it's incomplete and have some problems -- just a concept

**Comment by samdark** [comment]
The issue is fixed. Left open because @yiiliveext wants to add a test for it.
