### ISSUE TITLE
Why route collector is suggested to be created through container?

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/router#72]
In the README route collector is suggested to be created through container:

```php
$collector = $container->get(RouteCollectorInterface::class);
```

The question is why?

At the moment it is resolved to `Group`.
And it is the only implementation so far.

Is there supposed other implementations?
What extended features could it provide?

**Comment by viktorprogger** [comment]
I think there should be a set of conventions about readme and documentation for all packages to follow them. An answer to this question should be there in my opinion.

**Comment by hiqsol** [comment]
Ok. I've found why.
That's because of non obvious dependency to `MiddlewareDispatcher` which in turn depends on `MiddlewareFactory` and `MiddlewareStack`.
It should be represented in documentation!

**Comment by yiiliveext** [comment]
Because you can add routes dynamically before `Router` middleware will be executed.
