### ISSUE TITLE
Which one should be faster?

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/router#73]
Plain route list:

```php
$collector->addGroup(Group::create('/api',[
    Route::get('/posts'),
    Route::get('/post/{id:\d+}'),
    Route::get('/users'),
    Route::get('/user/{id:\d+}'),
]));
```

Or grouped:

```php
$collector->addGroup(Group::create('/api',[
    Group::create('/post', [
        Route::get('s'),
        Route::get('/{id:\d+}'),
    ]),
    Group::create('/user', [
        Route::get('s'),
        Route::get('/{id:\d+}'),
    ]),
]));
```

**Comment by samdark** [comment]
Both should give you similar results when used with router-fastroute. Do you have concerns about it?

**Comment by hiqsol** [comment]
No concerns.
There are two options. I just want to sort out for myself.
Which option should be used?
What is a reason to use `Group` ?

**Comment by samdark** [comment]
To group things i.e. prefix a group of routes with `/api`, add CORS middleware to this group etc.

**Comment by hiqsol** [comment]
> add CORS middleware to this group

@samdark How can I add a middleware to a group?

**Comment by samdark** [comment]
https://github.com/yiisoft/docs/blob/master/guide/en/runtime/routing.md
